sudo: false
language: scala
matrix:
  include:
    - scala: 2.10.6
      script: ./sbt ++$TRAVIS_SCALA_VERSION clean compile test && ./sbt ++$TRAVIS_SCALA_VERSION core:mima-report-binary-issues

    - scala: 2.11.8
      script: ./sbt ++$TRAVIS_SCALA_VERSION clean compile test && ./sbt ++$TRAVIS_SCALA_VERSION core:mima-report-binary-issues
notifications:
  irc:
    channels:
      - "chat.freenode.net#spire-math"
    on_success: change
    on_failure: always
