sudo: false
language: scala
scala: 
  - 2.11.8
  - 2.10.6
script: ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test && ./sbt ++$TRAVIS_SCALA_VERSION core:mima-report-binary-issues
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  irc:
    channels:
      - "chat.freenode.net#spire-math"
    on_success: change
    on_failure: always
