sudo: false
language: scala
matrix:
  include:
    - scala: 2.10.5
      script: ./sbt ++$TRAVIS_SCALA_VERSION clean compile lawsJVM/test && ./sbt ++$TRAVIS_SCALA_VERSION core:mima-report-binary-issues

    - scala: 2.11.7
      script: ./sbt ++$TRAVIS_SCALA_VERSION clean compile lawsJVM/test && ./sbt ++$TRAVIS_SCALA_VERSION core:mima-report-binary-issues
notifications:
  irc:
    channels:
      - "chat.freenode.net#spire-math"
    on_success: change
    on_failure: always
